# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: apurv.dev
google_analytics: apurvtwr
title: Apurv

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: kugelblitz

description: 
author:
  name: Apurv
  email: apurvtwr@gmail.com
  github: apurvtwr
  twitter: apurvtwr
  linkedin: asd123
  bio: Things on my mind in no specific order!

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
